name: Build Cross-Platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.6'

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          pkg-config libayatana-appindicator3-dev libgtk-3-dev

    # Build for Linux
    - name: Build Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o sorter-linux ./...

    # Build for Windows (No terminal/GUI mode)
    - name: Build Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -v -ldflags="-H=windowsgui" -o sorter-windows.exe ./...

    # Upload Linux Binary
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: sorter-linux
        if-no-files-found: error

    # Upload Windows Binary
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: sorter-windows.exe
        if-no-files-found: error
