# Upload Linux Binary
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: sorter-linux  # Changed from 'sorter'
        path: sorter

    # Upload Windows Binary
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: sorter-windows  # Changed from 'sorter'
        path: sorter.exe
